### Create new user
POST http://localhost:8000/api/register
Content-Type: application/json
Accept: application/json

{
    "name": "Roman Ojha",
    "email": "roman@gmail.com",
    "password": "romanojha",
    "password_confirmation":"romanojha",
    "tc": "true"
}

### Api to login the user
POST http://localhost:8000/api/login
Content-Type: application/json
Accept: application/json

{
    "email":"roman@gmail.com",
    "password":"razzroman"
}

### Api to logout the user
POST http://localhost:8000/api/logout
Accept : application/json
Authorization: Bearer 5|CUNgtx4a10MrBZTyqqzfne0TIRrNEebQyQyA842G

### Api to get user data
GET http://localhost:8000/api/get-user
Accept : application/json
Authorization: Bearer 5|CUNgtx4a10MrBZTyqqzfne0TIRrNEebQyQyA842G


### Api to change user password
POST http://localhost:8000/api/changepassword
Content-Type: application/json
Accept : application/json
Authorization: Bearer 5|CUNgtx4a10MrBZTyqqzfne0TIRrNEebQyQyA842G

{
    "password":"razzroman",
    "password_confirmation":"razzroman"
}